spring:
  application:
    name: demo

  datasource:
    url: jdbc:mariadb://192.168.133.140:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: sjb
    password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


server:
  port: 8089